[tool.poetry]
name = "script task"
version = "0.1.0"
description = ""
authors = ["VoitecP <piwowarski.connect@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.23"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
